---
- hosts: webservers
  become: true

  tasks:
    - name: "Updating the repo"
      apt:
         update_cache: yes

    - name: Installation PHP 7.4
      apt:
         name: php
         state: present
  
    - name: Install Apache HTTP Server on Debian
      apt:
         name: apache2
         state: latest

    - name: Start Apache HTTP Server and Enable it on Debian
      service:
         name: apache2
         state: started
         enabled: true

    - name: Delete content & directory
      file:
         state: absent
         path: /var/www/html/index.html


    - name: Copy index test page
      template:
         src: "/home/vagrant/ansible/index.php"
         dest: "/var/www/html/index.php"

    - name: Copy image
      copy:
         src: "/home/vagrant/ansible/bulgaria-map.png"
         dest: "/var/www/html/"

- hosts: dbservers
  become: true

  tasks:
    - name: Install MariaDB Server on CentOS
      yum:
         name: mariadb,mariadb-server
         state: present
         
    - name: Copy DB
      copy:
         src: "/home/vagrant/ansible/db_setup.sql"
         dest: "/home/vagrant/db/"

    - name: Start and enable MariaDB on CentOS
      service:
         name: mariadb
         state: started
         enabled: true
         
    - name: Stop Firewall
      service:
         name: firewalld
         state: stopped
         enabled: False
