---
- hosts: webservers
  become: true

  tasks:
    - name: "Updating the repo"
      apt:
         update_cache: yes

    - name: Installation PHP 7.4
      apt:
         name: php,php-mysql,libapache2-mod-php,php-cli
         state: present
  
    - name: Install Apache HTTP Server on Debian
      apt:
         name: apache2
         state: latest

    - name: Start Apache HTTP Server and Enable it on Debian
      service:
         name: apache2
         state: started
         enabled: true

    - name: Delete content & directory
      file:
         state: absent
         path: /var/www/html/index.html


    - name: Copy index test page
      template:
         src: "/home/vagrant/ansible/index.php"
         dest: "/var/www/html/index.php"

    - name: Copy image
      copy:
         src: "/home/vagrant/ansible/bulgaria-map.png"
         dest: "/var/www/html/"

    - name: Give insecure permissions to index.php
      file:
         path: /var/www/html/index.php
         owner: root
         group: root
         mode: '1777'

- hosts: dbservers
  become: true

  tasks:
    - name: Install MariaDB Server and python3-PyMySQL on CentOS
      yum:
         name: mariadb,mariadb-server,python3-PyMySQL
         state: present
         
    - name: Copy DB
      copy:
         src: "/home/vagrant/ansible/db_setup.sql"
         dest: "/home/vagrant/db/"

    - name: Start and enable MariaDB on CentOS
      service:
         name: mariadb
         state: started
         enabled: true

    - name: Stop Firewall
      service:
         name: firewalld
         state: stopped
         enabled: False
         
    - name: mysql_root_password
      mysql_user:
        login_user: web_user
        login_password: "Password1"
        user: root
        check_implicit_admin: true
        password: ""
        host: "db"

    - name: Import db_setup.sql
      mysql_db:
        state: import
        name: all
        target: /home/vagrant/db/db_setup.sql
